FROM --platform=linux/amd64 python:3.10-slim-bullseye
RUN apt-get update
RUN apt-get -y install curl vim python3-pyodbc unixodbc-dev unixodbc
RUN apt-get update
RUN apt-get -y install apt-transport-https
RUN apt-get -y install gcc gnupg libxml2-dev libxslt1-dev zlib1g-dev g++
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get -y install libc6:i386 libncurses5:i386 libstdc++6:i386 libuuid1:i386
RUN apt-get -y install git
RUN apt-get -y install wget
WORKDIR /usr/local
RUN wget https://s3.amazonaws.com/downloads.paperlessparts.com/Zen-Client-linux-x86_64-14.20.012.000.tar.gz
RUN tar -zxf Zen-Client-linux-x86_64-14.20.012.000.tar.gz
WORKDIR /usr/local/actianzen/etc
RUN ./clientpreinstall.sh
RUN ./clientpostinstall.sh
RUN rm /etc/odbc.ini
RUN ln -s /usr/local/actianzen/etc/odbc.ini /etc/odbc.ini
RUN ln -s /usr/local/actianzen/etc/odbcinst.ini /etc/odbcinst.ini
RUN /usr/bin/gpasswd -a root zen-data
ENV ACTIANZEN_ROOT=/usr/local/actianzen
ENV PATH=$PATH:$ACTIANZEN_ROOT/bin:/bin:/usr/bin
ENV LD_LIBRARY_PATH=$ACTIANZEN_ROOT/lib64:$ACTIANZEN_ROOT/lib:$ACTIANZEN_ROOT/bin:/usr/lib
ENV MANPATH=$MANPATH:$ACTIANZEN_ROOT/man