Paperless:
  dir_to_preserve: inforvisual
  slug: replace_me
  source_email: noreply@paperlessparts.com
  new_customer_emails: noreply@paperlessparts.com
  logpath: log.txt

INFORVISUAL:
  paperless_user: PPRLS

Exporters:
#  quotes:
#    interval: 1
#    should_update_quote_erp_code_in_paperless_parts: True

  orders:
    interval: 1
    update_customers: False
    send_email_when_customer_not_found: False
    vendor_variable: Workcenter Lookup
    pp_mat_id_variable: Material Pricing Lookup
    default_site_id: MTI
    create_purchased_component: False
    create_material: False
    leg_assembly: True
    pp_parts_per_material_unit_variable: Parts Per Material Stock Unit
    should_export_assemblies_with_duplicate_components: True
    should_update_quote_line_status: False

Importers:
  accounts:
    interval: 3
  materials:
    interval: 3
    bulk_enable: True
    filter:
      product_code__in:
        - HARDWARE
        - PAINT
        - RAW
    imported_columns:
      - column_name: 'material_id'
        source_column: 'id'
        default: 'N/A'
      - column_name: 'description'
        default: 'N/A'
      - column_name: 'user_1'
        default: 'N/A'
      - column_name: 'user_2'
        default: 'N/A'
      - column_name: 'user_3'
        default: 'N/A'
      - column_name: 'user_4'
        default: 'N/A'
      - column_name: 'user_5'
        default: 'N/A'
      - column_name: 'commodity_code'
        default: 'N/A'
  purchased_components:
    interval: 3
    bulk_enable: True
    import_from_purchase_orders: False
    filter:
      product_code__in:
        - HARDWARE
        - PAINT
        - RAW
#  repeat_part:
#    is_post_enabled: True

