Paperless:
  dir_to_preserve: jobscope
  slug: replace_me
  source_email: noreply@paperlessparts.com
  new_customer_emails: noreply@paperlessparts.com
  logpath: log.txt

Exporters:
  orders:
    interval: 1