class E2Config:
    def __init__(self, **kwargs):
        self.entered_by = kwargs.get('entered_by')
        self.tax_exempt_code = kwargs.get('tax_exempt_code')
        self.credit_card_terms_code = kwargs.get('credit_card_terms_code')
        self.default_work_center_name = kwargs.get('default_work_center_name')
        self.default_vendor_code_name = kwargs.get('default_vendor_code_name')
        self.raw_material_part_number_variable_name = kwargs.get('raw_material_part_number_variable_name')
        self.raw_material_row_lookup_variable_name = kwargs.get('raw_material_row_lookup_variable_name')
        self.vendor_code_operation_variable_name = kwargs.get('vendor_code_operation_variable_name')
        self.op_code_operation_variable_name = kwargs.get('op_code_operation_variable_name')
        self.setup_time_units = kwargs.get('setup_time_units', 'H')
        self.runtime_units = kwargs.get('runtime_units', 'H')
        self.should_update_e2_billing_address = kwargs.get('should_update_e2_billing_address')
        self.should_update_e2_payment_terms = kwargs.get('should_update_e2_payment_terms')
        self.should_create_e2_shipping_address = kwargs.get('should_create_e2_shipping_address')
        self.should_update_e2_customer_notes = kwargs.get('should_update_e2_customer_notes')
        self.should_update_e2_customer_sales_id = kwargs.get('should_update_e2_customer_sales_id')
        self.should_update_e2_part_revision = kwargs.get('should_update_e2_part_revision')
        self.should_update_e2_part_description = kwargs.get('should_update_e2_part_description')
        self.should_update_e2_purchased_components_data = kwargs.get('should_update_e2_purchased_components_data')
        self.should_create_e2_raw_material_record = kwargs.get('should_create_e2_raw_material_record')
        self.should_replace_e2_routing_for_existing_parts = kwargs.get('should_replace_e2_routing_for_existing_parts')
        self.should_replace_e2_bom_for_existing_parts = kwargs.get('should_replace_e2_bom_for_existing_parts')
        self.should_get_vend_code_from_operation_variable = kwargs.get('should_get_vend_code_from_operation_variable')
        self.should_create_order_line_items_as_processed = kwargs.get('should_create_order_line_items_as_processed')
        self.should_include_paperless_urls_in_job_notes = kwargs.get('should_include_paperless_urls_in_job_notes')
        self.should_update_e2_part_quantity_and_price = kwargs.get('should_update_e2_part_quantity_and_price')
        self.should_use_extended_part_quantity_and_price = kwargs.get('should_use_extended_part_quantity_and_price')
        self.should_populate_order_routing_for_add_ons = kwargs.get('should_populate_order_routing_for_add_ons')
        self.default_customer_currency_code = kwargs.get('default_customer_currency_code')
        self.default_sales_order_location = kwargs.get('default_sales_order_location')
        self.default_work_code = kwargs.get('default_work_code')
        self.default_routed_by_employee = kwargs.get('default_routed_by_employee')
        self.default_sales_order_fob = kwargs.get('default_sales_order_fob')
        self.should_export_assemblies_with_duplicate_components = kwargs.get(
            "should_export_assemblies_with_duplicate_components"
        )
        self.should_use_new_multiple_material_logic = kwargs.get('should_use_new_multiple_material_logic')
        self.material_op_quantity_required_var = kwargs.get('material_op_quantity_required_var')
        self.material_op_uom_var = kwargs.get('material_op_uom_var')
        self.material_default_uom = kwargs.get('material_default_uom')
        self.material_op_prod_code_var = kwargs.get('material_op_prod_code_var')
        self.material_default_prod_code = kwargs.get('material_default_prod_code')
