name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment & Build OpenSSL
        shell: cmd
        run: |
          Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe" -OutFile "nasm-installer.exe"
          echo "Downloaded NASM installer"

          start /wait nasm-installer.exe /S
          echo "NASM installed successfully"
        
          REM 1️⃣ Ensure NASM is Installed and in PATH
          set PATH=C:\Program Files\NASM;%PATH%
          where nasm
          nasm -v
      
          REM 4️⃣ Download and Extract OpenSSL
          powershell -Command "Invoke-WebRequest -Uri 'https://www.openssl.org/source/openssl-3.0.8.tar.gz' -OutFile 'openssl.tar.gz'"
          tar -xf openssl.tar.gz
          echo "Extracted OpenSSL"
      
          REM 5️⃣ Build OpenSSL with FIPS Mode
          echo %PATH%
          nasm -v
          cd openssl-3.0.8
          perl Configure VC-WIN64A fips
          nmake
          nmake install
          echo "OpenSSL Build Completed"
      
          REM 6️⃣ Verify OpenSSL Installation
          openssl version -a
          openssl fips

