name: Build Python Executable
run-name: builder
on: [push]
jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          choco install visualstudio2019buildtools cmake nasm perl -y
          choco install strawberryperl -y  # Needed for OpenSSL build

      - name: Download and Build FIPS-Compliant OpenSSL
        run: |
          Invoke-WebRequest -Uri "https://www.openssl.org/source/openssl-3.0.8.tar.gz" -OutFile "openssl-3.0.8.tar.gz"
          tar -xf openssl-3.0.8.tar.gz
          cd openssl-3.0.8
          perl Configure VC-WIN64A fips
          nmake
          nmake install
        shell: cmd

      - name: Download Python Source
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tgz" -OutFile "Python-3.11.5.tgz"
          tar -xf Python-3.11.5.tgz
        shell: cmd

      - name: Build Python with FIPS OpenSSL
        run: |
          cd Python-3.11.5
          PCbuild\build.bat -e -p x64 --openssl-dir="C:\Program Files\OpenSSL"
        shell: cmd

      - name: Verify Python Build is Using FIPS OpenSSL
        run: |
          python -c "import ssl; print(ssl.OPENSSL_VERSION)"
        shell: cmd

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile my_script.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: fips-python-executable
          path: dist/my_script.exe
