name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Visual Studio Build Tools & Persist PATH
        shell: cmd
        run: |
          echo %PATH%
        
          REM 1️⃣ Install Visual Studio Build Tools (`nmake`)
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041" -y
          echo "Installed Visual Studio Build Tools."
      
          REM 2️⃣ Install NASM
          powershell -Command "Invoke-WebRequest -Uri 'https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe' -OutFile 'nasm-installer.exe'"
          start /wait nasm-installer.exe /S
          echo "Installed NASM"
      
          REM 3️⃣ Load MSVC Environment & Add `nmake` to PATH
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
      
          REM 4️⃣ Ensure NASM and MSVC Tools are in PATH
          set PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools;%PATH%
      
          REM 5️⃣ Persist PATH for Future Steps
          echo PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools;%PATH%>> %GITHUB_ENV%

          echo "Detecting Visual Studio Installation..."
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set VS_PATH=%%i
          echo "Visual Studio Path: %VS_PATH%"
          dir "%VS_PATH%\VC\Tools\MSVC" /b

          echo "Searching for `nmake.exe`..."
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" /s /b | findstr nmake.exe
          dir "C:\Program Files\Microsoft Visual Studio\2022\BuildTools" /s /b | findstr nmake.exe
      
          REM 6️⃣ Verify Everything is Installed Correctly
          echo "Final PATH:"
          echo %PATH%
          where nasm
          nasm -v
          where nmake
          nmake /?

