name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download NASM Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe" -OutFile "nasm-installer.exe"
          echo "Downloaded NASM installer"

      - name: Install NASM Manually
        shell: cmd
        run: |
          start /wait nasm-installer.exe /S
          echo "NASM installed successfully"

      - name: Add NASM to PATH
        shell: cmd
        run: |
          setx PATH "%PATH%;C:\Program Files\NASM"
          set PATH=%PATH%;C:\Program Files\NASM
          echo "$PATH"
          where nasm || echo "NASM not found"

