name: Build Python Executable
run-name: builder
on: [push]
jobs:

  build:
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install Dependencies
        run: |
          grep -v '^pip' integrations/requirements.txt > integrations/filtered-requirements.txt
          cat integrations/filtered-requirements.txt
          pip install -r integrations/filtered-requirements.txt

      # Build python script into a single execute or app folder (macOS)
      - name: Install Nuitka
        run: |
          pip install nuitka

      - name: Build Executable
        run: |
          python -m nuitka --onefile --assume-yes-for-downloads --noinclude-dlls=openssl hello_world.py

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/hello_world.exe
          include-hidden-files: true
