name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Perl & NASM
        shell: powershell
        run: |
          choco install nasm --force --debug -y
          echo "Installed NASM"

      - name: Add NASM to PATH
        shell: cmd
        run: |
          setx PATH "%PATH%;C:\Program Files\NASM"
          set PATH=%PATH%;C:\Program Files\NASM
          where nasm

      - name: Verify NASM Installation
        shell: cmd
        run: |
          where nasm || echo "NASM still missing"
          dir C:\Program Files\NASM\nasm.exe
