name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment & Build OpenSSL
        shell: cmd
        run: |
          REM 1️⃣ Ensure NASM is Installed and in PATH
          set PATH=C:\Program Files\NASM;%PATH%
          where nasm
          nasm -v
      
          REM 2️⃣ Install Visual Studio Build Tools (`nmake`)
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041" -y
          echo "Installed Visual Studio Build Tools"
      
          REM 3️⃣ Load MSVC Environment
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          where nmake
      
          REM 4️⃣ Download and Extract OpenSSL
          powershell -Command "Invoke-WebRequest -Uri 'https://www.openssl.org/source/openssl-3.0.8.tar.gz' -OutFile 'openssl.tar.gz'"
          tar -xf openssl.tar.gz
          echo "Extracted OpenSSL"
      
          REM 5️⃣ Build OpenSSL with FIPS Mode
          cd openssl-3.0.8
          perl Configure VC-WIN64A fips --with-nasm="C:\Program Files\NASM\nasm.exe"
          nmake
          nmake install
          echo "OpenSSL Build Completed"
      
          REM 6️⃣ Verify OpenSSL Installation
          openssl version -a
          openssl fips

