name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools (MSVC)
        shell: powershell
        run: |
          choco install visualstudio2022buildtools visualstudio-installer -y
          echo "Installed Visual Studio Build Tools"

      - name: Install Perl & NASM
        shell: powershell
        run: |
          choco install strawberryperl nasm -y
          echo "Installed Perl and NASM"

      - name: Add Perl & NASM to PATH
        shell: cmd
        run: |
          setx PATH "%PATH%;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\bin"
          set PATH=%PATH%;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\bin"
          where perl
          where nasm

      - name: Verify Perl & NASM Installations
        shell: cmd
        run: |
          perl -v
          nasm -v

      - name: Download & Extract OpenSSL
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.openssl.org/source/openssl-3.0.8.tar.gz" -OutFile "openssl.tar.gz"
          tar -xf openssl.tar.gz
          echo "Extracted OpenSSL"

      - name: Build OpenSSL 3 with FIPS Mode
        shell: cmd
        run: |
          cd openssl-3.0.8
          for /d %%X in ("C:\Program Files\Microsoft Visual Studio\2022\*") do set VS_PATH=%%X
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          perl Configure VC-WIN64A fips
          nmake
          nmake install
          echo "OpenSSL Build Completed"

      - name: Verify OpenSSL Build
        shell: cmd
        run: |
          openssl version -a
          openssl fips
