name: Build Python Executable
run-name: builder
on: [push]
jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools (Includes nmake)
        shell: powershell
        run: |
          choco install visualstudio2022buildtools --package-parameters `
          "--add Microsoft.VisualStudio.Component.VC.CoreBuildTools `
          --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
          --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
          --add Microsoft.VisualStudio.Component.Windows11SDK.22621 `
          --add Microsoft.VisualStudio.Component.VC.CMake.Project"`
          echo "Installed Visual Studio Build Tools"

      - name: Debug Visual Studio Install
        shell: cmd
        run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022"

      - name: Verify `nmake` is Installed
        shell: cmd
        run: |
          for /d %%X in ("C:\Program Files\Microsoft Visual Studio\2022\*") do set VS_PATH=%%X
          echo Found Visual Studio Path: %VS_PATH%
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          where nmake

      - name: Download and Extract OpenSSL
        shell: powershell
        run: |
          $openssl_url = "https://www.openssl.org/source/openssl-3.0.8.tar.gz"
          $openssl_file = "openssl-3.0.8.tar.gz"
          Invoke-WebRequest -Uri $openssl_url -OutFile $openssl_file
          tar -xf $openssl_file
          cd openssl-3.0.8
          echo "Extracted OpenSSL"

      - name: Build OpenSSL with FIPS Mode
        shell: cmd
        run: |
          cd openssl-3.0.8
          for /d %%X in ("C:\Program Files\Microsoft Visual Studio\2022\*") do set VS_PATH=%%X
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          perl Configure VC-WIN64A fips
          nmake
          nmake install
          echo "OpenSSL Build Completed"

      - name: Download Python Source
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tgz" -OutFile "Python-3.11.5.tgz"
          tar -xf Python-3.11.5.tgz

      - name: Build Python with FIPS OpenSSL
        shell: cmd
        run: |
          cd Python-3.11.5
          for /d %%X in ("C:\Program Files\Microsoft Visual Studio\2022\*") do set VS_PATH=%%X
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          PCbuild\build.bat -e -p x64 --openssl-dir="C:\Program Files\OpenSSL"

      - name: Verify Python Build Uses FIPS OpenSSL
        shell: cmd
        run: |
          python -c "import ssl; print(ssl.OPENSSL_VERSION)"

      - name: Install PyInstaller
        shell: cmd
        run: python -m pip install pyinstaller

      - name: Build Executable
        shell: cmd
        run: pyinstaller --onefile my_script.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: fips-python-executable
          path: dist/my_script.exe
