name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Visual Studio Build Tools & Persist PATH
        shell: cmd
        run: |
          echo %PATH%
        
          REM 1️⃣ Install Visual Studio Build Tools (`nmake`)
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041" -y
          echo "Installed Visual Studio Build Tools."
      
          REM 2️⃣ Install NASM
          powershell -Command "Invoke-WebRequest -Uri 'https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe' -OutFile 'nasm-installer.exe'"
          start /wait nasm-installer.exe /S
          echo "Installed NASM"
      
          REM 3️⃣ Load MSVC Environment & Add `nmake` to PATH
          call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
      
          REM 4️⃣ Ensure NASM and MSVC Tools are in PATH
          set PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools;%PATH%
      
          REM 5️⃣ Persist PATH for Future Steps
          echo PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools;%PATH%>> %GITHUB_ENV%

          REM 1️⃣ Detect Visual Studio Build Tools Path
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set VS_PATH=%%i
          echo "Visual Studio Path: %VS_PATH%"
      
          REM 2️⃣ Run `vcvars64.bat` to set environment variables
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
      
          REM 3️⃣ Manually Add `nmake` to PATH
          set PATH=%VS_PATH%\VC\Tools\MSVC\*\bin\Hostx64\x64;%PATH%
          echo PATH=%VS_PATH%\VC\Tools\MSVC\*\bin\Hostx64\x64;%PATH%>> %GITHUB_ENV%
      
          REM 4️⃣ Verify `nmake` is available
          where nasm
          nasm -v
          where nmake
          nmake /?

      - name: Download and Extract OpenSSL
        shell: cmd
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://www.openssl.org/source/openssl-3.0.8.tar.gz' -OutFile 'openssl.tar.gz'"
          tar -xf openssl.tar.gz
          echo "Extracted OpenSSL"

      - name: Build OpenSSL with FIPS Mode
        shell: cmd
        run: |
          cd openssl-3.0.8
          perl Configure VC-WIN64A fips
          nmake
          nmake install
          echo "OpenSSL Build Completed"

      - name: Verify OpenSSL Build
        shell: cmd
        run: |
          openssl version -a
          openssl fips
