name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment & Build OpenSSL
        shell: cmd
        run: |
          REM 1️⃣ Download and Install NASM
          powershell -Command "Invoke-WebRequest -Uri 'https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe' -OutFile 'nasm-installer.exe'"
          start /wait nasm-installer.exe /S
          echo "Installed NASM"
      
          REM 2️⃣ Ensure NASM is in PATH
          set PATH=C:\Program Files\NASM;%PATH%
          where nasm
          nasm -v
          echo %PATH%

