name: Build FIPS-Compliant OpenSSL
run-name: builder
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Persist `PATH` for NASM & MSVC
        shell: cmd
        run: |
          echo "Setting up PATH for NASM and MSVC..."
      
          REM 1️⃣ Ensure NASM and MSVC are both in PATH (single command)
          set PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64;%PATH%
          
          REM 2️⃣ Persist the updated PATH to be used in all future steps
          echo PATH=C:\Program Files\NASM;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64;%PATH%>> %GITHUB_ENV%
      
          REM 3️⃣ Verify the PATH update
          echo "Final PATH:"
          echo %PATH%
          where nasm
          where nmake
          nmake /?

